In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_excel('Sample1.xlsx')
df

,Fiscal Quarter ID,Fiscal Period ID,Sales Level 1,Sales Level 2,Sales Level 3,Internal Business Entity Description,Internal Sub Business Entity Description,Corporate Bookings Flag,Organization Code,Technology Group,...,Product Classification,Software Type,Revenue Recognition Flag,Accounting Rule,Product Family,Txn Net Price Indicator,XCAT Flag,Business Model,Org Category,Product Bookings Net
0,2025Q2,202501,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Perpetual,Y,NaN,HCIPPSW,=,N,Physical Delivery,Adj. Org,-80.06
1,2025Q2,202502,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,On-Premise Subscription,Y,NaN,UCSHX,=,N,Physical Delivery,Adj. Org,-10774.67
2,2025Q2,202503,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Subscription,Y,NaN,HCIPS,=,N,Non Factory,Adj. Org,-754.32
3,2025Q2,202501,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Subscription,Y,NaN,HCISW,=,N,Non Factory,Adj. Org,-9439.98
4,2025Q2,202502,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Subscription,Y,NaN,HXDP,=,N,Non Factory,Adj. Org,-38.30
5,2025Q2,202503,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Subscription,Y,NaN,HXDPMKT,=,N,Non Factory,Adj. Org,-56571.44
6,2025Q2,202501,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Subscription,Y,NaN,HXEALTB,=,N,Non Factory,Adj. Org,-131.59
7,2025Q2,202502,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Subscription,Y,NaN,HXLTB,=,N,Non Factory,Adj. Org,-10985.39
8,2025Q2,202503,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HCI6CPU,=,N,Physical Delivery,Adj. Org,-974.07
9,2025Q2,202501,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HCI6HW,=,N,Physical Delivery,Adj. Org,-1662.07
10,2025Q2,202502,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HCI6MEM,=,N,Physical Delivery,Adj. Org,-1990.61
11,2025Q2,202503,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HCI6NVM,=,N,Physical Delivery,Adj. Org,-270.27
12,2025Q2,202501,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HCI6SSD,=,N,Physical Delivery,Adj. Org,-542.86
13,2025Q2,202502,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HCICPU,=,N,Physical Delivery,Adj. Org,-380.55
14,2025Q2,202503,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HCIHW,=,N,Physical Delivery,Adj. Org,-463.23
15,2025Q2,202501,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HCIMEM,=,N,Physical Delivery,Adj. Org,-2672.59
16,2025Q2,202502,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HCINVM,=,N,Physical Delivery,Adj. Org,-1205.29
17,2025Q2,202503,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HCISSD,=,N,Physical Delivery,Adj. Org,-2599.30
18,2025Q2,202501,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HXCPU,=,N,Physical Delivery,Adj. Org,-8860.18
19,2025Q2,202502,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HXHDD,=,N,Physical Delivery,Adj. Org,-2897.27
20,2025Q2,202503,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HXMEM,=,N,Physical Delivery,Adj. Org,-28140.26
21,2025Q2,202501,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HXNVME,=,N,Physical Delivery,Adj. Org,-11530.12
22,2025Q2,202502,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,UNKNOWN,Y,NaN,HXSSD,=,N,Physical Delivery,Adj. Org,-20371.57
23,2025Q2,202503,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Intersight,Y,-,CSPTG,...,Software,On-Premise Perpetual,Y,NaN,UCSM,=,N,Physical Delivery,Adj. Org,-440.40
24,2025Q2,202501,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Intersight,Y,-,CSPTG,...,Software,On-Premise Perpetual,Y,NaN,UCSMC,=,N,Physical Delivery,Adj. Org,-0.09
25,2025Q2,202502,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Intersight,Y,-,CSPTG,...,Software,On-Premise Perpetual,Y,NaN,UCSPPSW,=,N,Physical Delivery,Adj. Org,-17012.00
26,2025Q2,202503,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Intersight,Y,-,CSPTG,...,Software,Hybrid,Y,NaN,DCMSAAS,=,N,Non Factory,Adj. Org,-116580.68
27,2025Q2,202501,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Intersight,Y,-,CSPTG,...,Software,Hybrid,Y,NaN,DCMSWPA,=,Y,XCAT-MSJ,Adj. Org,-1306.01
28,2025Q2,202502,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Intersight,Y,-,CSPTG,...,Software,Hybrid,Y,NaN,IWOA,=,N,Non Factory,Adj. Org,-25537.53
29,2025Q2,202503,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Intersight,Y,-,CSPTG,...,Software,Hybrid,Y,NaN,IWOA,=,N,Non Factory,Adj. Org,-25537.53

To show Grandtotals and Subtotals, using margins=True

In [7]:
p=pd.pivot_table(df,index='Business Model',columns=['Fiscal Period ID','Fiscal Quarter ID'],values='Product Bookings Net',aggfunc='sum',margins=True)

In [8]:
p

Fiscal Period ID     202501    202502     202503        All
Fiscal Quarter ID    2025Q2    2025Q2     2025Q2
Business Model
Non Factory        -9571.57 -36561.22 -199443.97 -245576.76
Physical Delivery -25347.97 -54631.96  -32887.53 -112867.46
XCAT-MSJ           -1306.01       NaN        NaN   -1306.01
All               -36225.55 -91193.18 -232331.50 -359750.23

# Save the pivot table to an excel file

In [9]:
with pd.ExcelWriter('newpivotbookings.xlsx',engine='xlsxwriter') as writer:
    p.to_excel(writer,sheet_name='pivot1')
print('File downloaded')

File downloaded